#!/bin/bash

margin=10
proxy1="bin/proxy log/1-1.log $1 8888 1.0.0.1 5.0.0.1 5300 3.0.0.1"
proxy2="bin/proxy log/1-2.log $1 8889 2.0.0.1 5.0.0.1 5300 4.0.0.1"
dns="bin/nameserver -r log/1-ns.log 5.0.0.1 5300 topos/topo1/topo1.servers topos/topo1/topo1.lsa"

echo "start netsim"
pushd netsim
./netsim.py ../topos/topo1 start
popd

echo "start nameserver..."
$dns 2> log/1-ns-v.log&

echo "start proxy..."
$proxy1 2> log/1-1-v.log&
$proxy2 2> log/1-2-v.log&

echo "wait for start video..."
sleep $margin

echo "run netsim..."
pushd netsim
./netsim.py -l ../log/1-n.log ../topos/topo1 run
popd

echo "wait for stop video..."
sleep $margin

echo "stop..."
killall bin/proxy
killall bin/nameserver
